---
title: "Statistical Rethinking"
author: "Anne"
date: "6/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval = F}
remove.packages("rstan")
if (file.exists(".RData")) file.remove(".RData")

install.packages("Rcpp", repos = "https://rcppcore.github.io/drat")
library(Rcpp)

Sys.setenv(MAKEFLAGS = "-j4")

install.packages("rstan", type = "source")
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

install.packages(c("coda", "mvtnorm", "devtools", "dagitty", "cli"))
library(devtools)

devtools::install_github("rmcelreath/rethinking")

```

# Grid Approximation 
```{r}
# define grid 
p_grid <- seq(from=0, to =1, length.out = 20)

# define prior
prior <- rep(1,20)

# compute likelihood at each value in grid
likelihood <- dbinom(6, size = 9, prob = p_grid)

# compute product of likelihood and prior
unstand.posterior <- likelihood*prior

# standardize the posterior, so it sums to 1
posterior <- unstand.posterior / sum(unstand.posterior)

plot(p_grid, posterior, type = "b", 
     xlab = "probabiloty of water", ylab = "posterior probability", 
     main = "20 points")


# define grid 
p_grid <- seq(from=0, to =1, length.out = 5)

# define prior
prior <- rep(1,5)

# compute likelihood at each value in grid
likelihood <- dbinom(6, size = 9, prob = p_grid)

# compute product of likelihood and prior
unstand.posterior <- likelihood*prior

# standardize the posterior, so it sums to 1
posterior <- unstand.posterior / sum(unstand.posterior)

plot(p_grid, posterior, type = "b", 
     xlab = "probabiloty of water", ylab = "posterior probability", 
     main = "5 points")


# define grid 
p_grid <- seq(from=0, to =1, length.out = 20)

# define prior
prior <- ifelse(p_grid < 0.5, 0, 1)

# compute likelihood at each value in grid
likelihood <- dbinom(6, size = 9, prob = p_grid)

# compute product of likelihood and prior
unstand.posterior <- likelihood*prior

# standardize the posterior, so it sums to 1
posterior <- unstand.posterior / sum(unstand.posterior)

plot(p_grid, posterior, type = "b", 
     xlab = "probabiloty of water", ylab = "posterior probability", 
     main = "20 points")


# define grid 
p_grid <- seq(from=0, to =1, length.out = 20)

# define prior
prior <- exp(-5*abs(p_grid-0.5))
  
# compute likelihood at each value in grid
likelihood <- dbinom(6, size = 9, prob = p_grid)

# compute product of likelihood and prior
unstand.posterior <- likelihood*prior

# standardize the posterior, so it sums to 1
posterior <- unstand.posterior / sum(unstand.posterior)

plot(p_grid, posterior, type = "b", 
     xlab = "probabiloty of water", ylab = "posterior probability", 
     main = "20 points")

```
# Quadratic Approximation

```{r}
library(rethinking)
globe.qa <- quap(
  alist(
    W ~ dbinom(W+L, p), # bionomial likelihood
    p ~ dunif(0,1) #uniform prior
  ), 
  data = list(W=6, L=3))

# display summary of quadratic approximation
precis(globe.qa)

# analytical calculation 
W <- 6
L <- 3

curve(dbeta(x, W+1, L+1), from = 0, to = 1)

# quadratic approximation
curve(dnorm(x, 0.67, 0.16), lty = 2, add = T)

```


